### YamlMime:ManagedReference
items:
- uid: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  commentId: T:Yort.OnlineEftpos.OnlineEftposApiEnvironment
  id: OnlineEftposApiEnvironment
  parent: Yort.OnlineEftpos
  children:
  - Yort.OnlineEftpos.OnlineEftposApiEnvironment.Live
  - Yort.OnlineEftpos.OnlineEftposApiEnvironment.Sandbox
  - Yort.OnlineEftpos.OnlineEftposApiEnvironment.Uat
  langs:
  - csharp
  - vb
  name: OnlineEftposApiEnvironment
  nameWithType: OnlineEftposApiEnvironment
  fullName: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  type: Enum
  source:
    id: OnlineEftposApiEnvironment
    path: ''
    startLine: 3801
  assemblies:
  - cs.temp.dll
  namespace: Yort.OnlineEftpos
  summary: "\nRepresents the possible production and sandbox environments for the Online Eftpos API.\n"
  example: []
  syntax:
    content: public enum OnlineEftposApiEnvironment
    content.vb: Public Enum OnlineEftposApiEnvironment
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Yort.OnlineEftpos.OnlineEftposApiEnvironment.Sandbox
  commentId: F:Yort.OnlineEftpos.OnlineEftposApiEnvironment.Sandbox
  id: Sandbox
  parent: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  langs:
  - csharp
  - vb
  name: Sandbox
  nameWithType: OnlineEftposApiEnvironment.Sandbox
  fullName: Yort.OnlineEftpos.OnlineEftposApiEnvironment.Sandbox
  type: Field
  source:
    id: Sandbox
    path: ''
    startLine: 3806
  assemblies:
  - cs.temp.dll
  namespace: Yort.OnlineEftpos
  summary: "\nDevelopment/test environment.\n"
  example: []
  syntax:
    content: Sandbox = 0
    return:
      type: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Yort.OnlineEftpos.OnlineEftposApiEnvironment.Uat
  commentId: F:Yort.OnlineEftpos.OnlineEftposApiEnvironment.Uat
  id: Uat
  parent: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  langs:
  - csharp
  - vb
  name: Uat
  nameWithType: OnlineEftposApiEnvironment.Uat
  fullName: Yort.OnlineEftpos.OnlineEftposApiEnvironment.Uat
  type: Field
  source:
    id: Uat
    path: ''
    startLine: 3810
  assemblies:
  - cs.temp.dll
  namespace: Yort.OnlineEftpos
  summary: "\nUser acceptance test environment.\n"
  example: []
  syntax:
    content: Uat = 1
    return:
      type: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Yort.OnlineEftpos.OnlineEftposApiEnvironment.Live
  commentId: F:Yort.OnlineEftpos.OnlineEftposApiEnvironment.Live
  id: Live
  parent: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  langs:
  - csharp
  - vb
  name: Live
  nameWithType: OnlineEftposApiEnvironment.Live
  fullName: Yort.OnlineEftpos.OnlineEftposApiEnvironment.Live
  type: Field
  source:
    id: Live
    path: ''
    startLine: 3814
  assemblies:
  - cs.temp.dll
  namespace: Yort.OnlineEftpos
  summary: "\nLive production environment for real transaction.\n"
  example: []
  syntax:
    content: Live = 2
    return:
      type: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Yort.OnlineEftpos
  commentId: N:Yort.OnlineEftpos
  isExternal: false
  name: Yort.OnlineEftpos
  nameWithType: Yort.OnlineEftpos
  fullName: Yort.OnlineEftpos
- uid: Yort.OnlineEftpos.OnlineEftposApiEnvironment
  commentId: T:Yort.OnlineEftpos.OnlineEftposApiEnvironment
  parent: Yort.OnlineEftpos
  isExternal: false
  name: OnlineEftposApiEnvironment
  nameWithType: OnlineEftposApiEnvironment
  fullName: Yort.OnlineEftpos.OnlineEftposApiEnvironment
